version: '3.9'

services:
  postgres:
    stdin_open: true # docker run -i
    tty:        true # docker run -t
    restart: on-failure
    container_name: onramp-pg
    domainname: postgres.onramp.com
    hostname: postgres
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    shm_size: '2g'
    image: "onramp/postgres"
    volumes:
    - onramp-pg:/var/lib/postgresql/data
    - ./sql:/app/sql
    - $HOME/.psql_history:/app/.psql_history

  dev:
    stdin_open: true # docker run -i
    tty:        true # docker run -t
    restart: on-failure
    container_name: onramp-dev
    domainname: dev.onramp.com
    hostname: dev
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: "onramp/onramp"
    command: "dev -c src/.air.toml"
    ports:
      - 9090:9090
    volumes:
      - ./app:/app

volumes:
  onramp-pg: {}

